# Generated by Django 3.1.7 on 2021-08-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbUiElementInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('page', models.CharField(max_length=128)),
                ('component', models.CharField(max_length=128)),
                ('find_by', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
                ('parent_find_by', models.CharField(blank=True, max_length=128, null=True)),
                ('parent_value', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(max_length=50)),
                ('is_active', models.IntegerField(blank=True, db_column='isactive', null=True)),
                ('insert_time', models.DateTimeField(auto_now_add=True, db_column='inserttime')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='updatetime')),
            ],
            options={
                'db_table': 'tb_ui_element_info',
                'managed': False,
            },
        ),
    ]
